### ISSUE TITLE
Chaper 12.2.1 Problems when exposing Services through Ingress

### ISSUE THREAD

**Issue by Bonjaski** [luksa/kubernetes-in-action-2nd-edition#15]
### Environments
- **Cluster version**: v1.22.6
- **Virtual Machine**: Oracle VM
- **CNI**: Calico

- **Resources**: 

[Ingress Controller] 
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/baremetal/deploy.yaml`

[Pods, Services]
https://github.com/luksa/kubernetes-in-action-2nd-edition/tree/master/Chapter12/SETUP

### YAML FILE

**[Service]**
```
apiVersion: v1
kind: Service
metadata:
  name: kiada
spec:
  type: ClusterIP
  selector:
    app: kiada
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
```

**[Ingress]**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiada-example-com
spec:
  rules:
  - host: kiada.example.com
    http:
      paths:
      - path: /        
        pathType: Prefix
        backend:
          service:    
            name: kiada
            port:
              number: 80
```

### Problem
- Chapter 12.2.1 Exposing a Service through an Ingress

When I tried to create ingress objects as following up on chapter 12, However I could not progress to the next step because the kiada service failed to find endpoints. 

### To Reproduce
- Create the Ingress Object

### Description about Resource

**kiada service**
```
root@k8s-m:~# kubectl describe svc kiada
Name:              kiada
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          app=kiada
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.111.148.71
IPs:               10.111.148.71
Port:              http  80/TCP
TargetPort:        8080/TCP
Endpoints:         <none>
Port:              https  443/TCP
TargetPort:        8443/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

**kiada Ingress**
```
Name:             kiada-example-com
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host               Path  Backends
  ----               ----  --------
  kiada.example.com  
                     /   kiada:80 (<error: endpoints "kiada" not found>)
Annotations:         <none>
Events:              <none>
```

Please give me any suggestions to proceed Ingress chapter.
